import type { NextPage } from 'next';
import styled from 'styled-components';
import Head from 'next/head';
import NavBar from 'components/NavBar/NavBar';
// import Hero from 'components/Hero/Hero';
import DynamicHero from 'components/Hero/DynamicHero';
import Slider from 'components/Slider/Slider';
import { sliderMedia } from 'components/Slider/sliderMedia';

const AppContainer = styled.div`
  min-height: 100vh;
  width: 100%;
  background-color: ${(props) => props.theme.colors.bgMain};
  color: ${(props) => props.theme.colors.textMain};
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: start;
`;

const Home: NextPage = () => {
  return (
    <AppContainer>
      <Head>
        <title>HDL Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <NavBar />
      <DynamicHero />

      <Slider>
        {sliderMedia.map((nft) => (
          <div key={nft.id}>
            <video loop autoPlay muted>
              <source src={nft.video_url} type="video/mp4" />
            </video>
          </div>
        ))}
      </Slider>
    </AppContainer>
  );
};

export default Home;
