import type { NextPage } from 'next';
import styled from 'styled-components';
import Head from 'next/head';
import Header from 'components/Header/Header';

const AppContainer = styled.div`
  min-height: 100vh;
  background-color: ${(props) => props.theme.colors.bgMain};
  display: flex;
  align-items: flex-start;
`;

const Home: NextPage = () => {
  return (
    <AppContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </AppContainer>
  );
};

export default Home;
