/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next';
import styled from 'styled-components';
import Head from 'next/head';
import NavBar from 'components/NavBar/NavBar';
import DynamicHero from 'components/Hero/DynamicHero';
import Slider from 'components/Slider/Slider';
import { sliderMedia } from 'components/Slider/sliderMedia';

const AppContainer = styled.div`
  min-height: 100vh;
  width: 100%;
  background-color: ${(props) => props.theme.colors.bgMain};
  color: ${(props) => props.theme.colors.textMain};
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: start;

  p {
    color: ${(props) => props.theme.colors.textOffset};
    padding: 50px;
    text-align: center;
    @media (max-width: 500px) {
      padding: 25px;
    }
  }
`;

const Home: NextPage = () => {
  return (
    <AppContainer>
      <Head>
        <title>HDL Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <NavBar />
      <DynamicHero />

      <Slider>
        {sliderMedia.map((nft) => (
          <div key={nft.id}>
            <img src={nft.video_url} alt="slide" />
          </div>
        ))}
      </Slider>
      <p>
        HDL will mint its iconic corporate pigeon logo for free for the public
        to own, the minting will be a 72 hour window. The logo NFT’s will come
        in several varieties with varying degrees of rarity. Future utility will
        be announced.
      </p>
    </AppContainer>
  );
};

export default Home;
